/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mt4j_input_inputSources_MTDevInputSource */

#ifndef _Included_org_mt4j_input_inputSources_MTDevInputSource
#define _Included_org_mt4j_input_inputSources_MTDevInputSource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mt4j_input_inputSources_MTDevInputSource
 * Method:    openDevice
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_mt4j_input_inputSources_MTDevInputSource_openDevice
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_mt4j_input_inputSources_MTDevInputSource
 * Method:    loadDeviceCaps
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mt4j_input_inputSources_MTDevInputSource_loadDeviceCaps
  (JNIEnv *, jobject);

/*
 * Class:     org_mt4j_input_inputSources_MTDevInputSource
 * Method:    startEventLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mt4j_input_inputSources_MTDevInputSource_startEventLoop
  (JNIEnv *, jobject);

/*
 * Class:     org_mt4j_input_inputSources_MTDevInputSource
 * Method:    closeDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mt4j_input_inputSources_MTDevInputSource_closeDevice
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_mt4j_input_inputSources_MTDevInputSource_ABS_MT_CONSTANT */

#ifndef _Included_org_mt4j_input_inputSources_MTDevInputSource_ABS_MT_CONSTANT
#define _Included_org_mt4j_input_inputSources_MTDevInputSource_ABS_MT_CONSTANT
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_mt4j_input_inputSources_MTDevInputSource_SYN_CONSTANT */

#ifndef _Included_org_mt4j_input_inputSources_MTDevInputSource_SYN_CONSTANT
#define _Included_org_mt4j_input_inputSources_MTDevInputSource_SYN_CONSTANT
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
